version: '3.7'

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 19000:19000
      - 19001:19001
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
